from pathlib import Path
import subprocess


def generate_test(target: Path) -> Path:
    test = target.parent / f"test_{target.stem}.py"
    test.write_text(
        "import unittest\n"
        "import importlib.util\n"
        "from pathlib import Path\n\n"
        "def _load():\n"
        f"    p = Path(r'{str(target)}')\n"
        "    spec = importlib.util.spec_from_file_location('m', p)\n"
        "    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m\n\n"
        "class TestAutoGenerated(unittest.TestCase):\n"
        "    def test_module_loads(self):\n"
        "        self.assertIsNotNone(_load())\n\n"
        "if __name__ == '__main__':\n"
        "    unittest.main()\n"
    )
    return test


def patch_common_syntax_error(target: Path):
    text = target.read_text(encoding='utf-8', errors='ignore')
    if "pritn(" in text:
        target.write_text(text.replace("pritn(", "print("))
        return True
    return False


def run_loop(target_file: str, retries: int = 3):
    target = Path(target_file)
    test = generate_test(target)
    logs = []
    for i in range(1, retries + 1):
        proc = subprocess.run(
            ["python3", "-m", "unittest", "discover", "-s", str(test.parent), "-p", test.name, "-v"],
            capture_output=True,
            text=True,
        )
        logs.append((i, proc.returncode, proc.stdout + proc.stderr))
        if proc.returncode == 0:
            return True, logs
        if not patch_common_syntax_error(target):
            break
    return False, logs
